import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useWallet } from "use-wallet";
import { useContractMethods } from "../hooks/useContractMethods";
import styles from "../styles/Home.module.css";

const connectWallet = async () => {
  return await window.ethereum.request({
    method: "wallet_addEthereumChain",
    params: [
      {
        chainId: "0x13881",
        chainName: "Matic",
        rpcUrls: ["https://rpc-mumbai.maticvigil.com/"],
        nativeCurrency: {
          name: "MATIC",
          symbol: "MATIC",
          decimals: 18,
        },
      },
    ],
  });
};

const Home: NextPage = () => {
  const wallet = useWallet();
  const { claim, getUserTokens } = useContractMethods();
  const [tokens, setTokens] = useState<any[]>();

  useEffect(() => {
    if (wallet?.account) {
      const timerId = setInterval(async () => {
        const res = await getUserTokens();
        setTokens(res);
      }, 1000);
      return () => {
        clearInterval(timerId);
      };
    }
  }, [wallet?.account, getUserTokens]);

  console.log(wallet);
  if (!wallet.isConnected()) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>AE Studio Awesome NFT</h1>

          <p className={styles.description}>
            <button
              className={styles.button}
              onClick={async () => {
                await connectWallet();
                wallet.connect("injected");
              }}
            >
              Connect wallet
            </button>
          </p>
        </main>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Mint your awesome NFT here!</h1>

        <p className={styles.description}>
          <button
            className={styles.button}
            onClick={async () => {
              await claim();
            }}
          >
            Claim
          </button>
        </p>

        {tokens?.map((token) => {
          return (
            <div key={"img" + token}>
              <Image
                src={`/images/${token}.png`}
                width={64}
                height={64}
                alt="my nft"
              />
              <span>NFT #{token}</span>
            </div>
          );
        })}
      </main>
    </div>
  );
};

export default Home;
